services:
  wireguard:
    image: ghcr.io/doyunshin/wireguard-manager:latest
    container_name: wg
    ports:
      - "51820:51820/udp"
      - "5000:5000"
    volumes:
      - ./data:/app/data
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    networks:
      inside
    restart: always

networks:
  inside:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.0.0/24"
          gateway: "192.168.0.254"
