services:
  wireguard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wg
    ports:
      - "51820:51820/udp"
      - "5000:5000"
    volumes:
      - ./data:/app/data
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: always

networks:
  outside:
    driver: macvlan
    driver_opts:
      parent: enp0s25
    ipam:
      config:
        - subnet: