name: Build and deploy frontend

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['22.x']

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Copy lock file
      run: cp frontend/pnpm-lock.yaml .

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
      
    - name: Install dependencies
      working-directory: ./frontend
      run: pnpm install

    - name: Run build
      working-directory: ./frontend
      run: pnpm build

    - name: Set date environment variable
      run: echo "DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

    - name: Upload dist file
      uses: actions/upload-artifact@v4
      with:
        include-hidden-files: true
        name: frontend-${{ env.DATE }}
        path: frontend/build

